language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - python setup.py install
  - pip install git+https://github.com/chfw/pyexcel.git
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install -r tests/requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install -r tests/requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install -r tests/requirements3.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install -r tests/requirements3.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then pip install git+https://github.com/eea/odfpy.git; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then pip install -r tests/requirements.txt; fi
  - pip install -r tests/requirements.txt 
script:
  make test
after_success:
  codecov
